'use strict';
// Značky kol: kanonický název, cenová třída (brandTier 1–5), aliasy a překlepy, nápovědy typu podle modelu.
//
// brandTier – typická cenová hladina značky (u použitých kol):
//   1 = levné / supermarketové / no-name / levná čínská elektrokola / retro (Favorit, Eska)
//   2 = rozpočtové značky (Author, CTM, Leader Fox, 4ever, Rock Machine, Btwin, Crussis, Apache …)
//   3 = střední třída (Giant, Cube, Merida, KTM, Ghost, Kellys, Superior, GT, Marin, Bulls …)
//   4 = prémiové (Specialized, Trek, Cannondale, Scott, Canyon, Orbea, Focus, BMC, YT, Haibike …; dětské Kubikes, Academy, Puky)
//   5 = špička / butik (Santa Cruz, Yeti, Pivot, Pinarello, Colnago, Cervélo, Riese & Müller, Moustache; dětské Woom, Early Rider)
//
// Aliasy se porovnávají s textem po keyOf() (bez diakritiky, malá písmena, slova oddělená mezerou), vždy na celá slova.
// `strict: true` = alias je zároveň běžné slovo („Focus“, „Rose“, „Kona“ …) → počítá se jen s velkým počátečním
// písmenem v původním textu nebo v kontextu slova „kolo“.
// `kind`: 'kids' (dětská značka), 'ebike' (jen/hlavně elektrokola), 'bmx', 'road', 'vintage', 'cheap_ebike', 'folding'.
// `models`: [regulární výraz nad keyOf textem, bikeType] – první shoda vyhrává, platí jen u dané značky.

/** @typedef {{name: string, tier: number, aliases: string[], strict?: boolean, kind?: string, models?: Array<[string, string]>}} BrandDef */

/** @type {BrandDef[]} */
const BRANDS = [
  // --- globální prémiové / střední značky ---
  {
    name: 'Specialized', tier: 4, aliases: ['specialized', 'specialised', 'specializet', 'specilized', 'specialiazed', 'specailized', 'specializd', 's works', 'sworks'],
    models: [
      ['\\b(turbo )?kenevo\\b|\\b(turbo )?levo\\b', 'ebike_mtb_full'],
      ['\\bturbo tero\\b|\\btero\\b', 'ebike_mtb'],
      ['\\b(turbo )?vado\\b', 'ebike_trekking'],
      ['\\b(turbo )?como\\b', 'ebike_city'],
      ['\\b(turbo )?creo\\b', 'ebike_road'],
      ['\\bhotwalk\\b', 'balance'],
      ['\\b(hotrock|riprock|jett)\\b', 'kids'],
      ['\\bstumpjumper (ht|hardtail)\\b|\\bepic (ht|hardtail)\\b', 'mtb_hardtail'],
      ['\\b(stumpjumper|stumpy|enduro|epic|camber|demo|status|fsr|safire|era|rumor|big hit|pitch fsr|sx trail|sx|kenevo sl)\\b', 'mtb_full'],
      ['\\b(rockhopper|rock hopper|chisel|fuse|pitch|hardrock|hard rock|myka|stumpjumper m2|jynx)\\b', 'mtb_hardtail'],
      ['\\b(diverge|crux|sequoia|awol)\\b', 'gravel'],
      ['\\b(tarmac|allez|roubaix|aethos|venge|shiv|ruby|dolce|amira|transition)\\b', 'road'],
      ['\\b(sirrus|crosstrail|cross trail|ariel|vita)\\b', 'cross'],
      ['\\b(p 3|p3|p 2|p slope|p 1)\\b', 'dirt'],
      ['\\b(fatboy)\\b', 'fatbike'],
    ],
  },
  {
    name: 'Trek', tier: 4, aliases: ['trek', 'treck'],
    models: [
      ['\\b(rail|fuel exe|e caliber|powerfly fs)\\b', 'ebike_mtb_full'],
      ['\\bpowerfly\\b', 'ebike_mtb'],
      ['\\b(allant 7s|allant 8s|allant 9|verve \\d+ ?s|district \\d+ ?s|dual sport \\d+ ?s)\\b', 'ebike_trekking'],
      ['\\b(precaliber|wahoo|roscoe 20|roscoe 24|mt 200|mt 220|jet)\\b', 'kids'],
      ['\\b(fuel ex|fuel|slash|remedy|session|top fuel|topfuel|supercaliber|full stache|scratch|lush)\\b', 'mtb_full'],
      ['\\b(marlin|x caliber|xcaliber|procaliber|roscoe|stache|superfly|skye|cali|4300|4500|6000|8000|3700|3900|820)\\b', 'mtb_hardtail'],
      ['\\b(checkpoint)\\b', 'gravel'],
      ['\\b(boone|crockett)\\b', 'cyclocross'],
      ['\\b(emonda|madone|domane|speed concept|lexa|1 1|1 2|1 5|2 1|2 3|5200|5500|alpha)\\b', 'road'],
      ['\\b(fx|ds|dual sport)\\b', 'cross'],
      ['\\b(allant|verve|district|zektor)\\b', 'city'],
      ['\\bfarley\\b', 'fatbike'],
      ['\\bticket\\b', 'dirt'],
    ],
  },
  {
    name: 'Giant', tier: 3, aliases: ['giant', 'gaint', 'gigant'],
    models: [
      ['\\b(trance x e|trance e|reign e|stance e)\\b', 'ebike_mtb_full'],
      ['\\b(fathom e|talon e|xtc e)\\b', 'ebike_mtb'],
      ['\\b(explore e|roam e|anytour e|dailytour e|entour e)\\b', 'ebike_trekking'],
      ['\\b(road e|revolt e)\\b', 'ebike_road'],
      ['\\b(arx|animator|xtc jr|talon jr|xtc sl jr|stp)\\b', 'kids'],
      ['\\b(trance|reign|anthem|stance|glory|faith|nrs)\\b', 'mtb_full'],
      ['\\b(talon|xtc|fathom|atx|revel|rincon|terrago|yukon|boulder)\\b', 'mtb_hardtail'],
      ['\\b(tcr|propel|defy|contend|ocr|scr|trinity|tcr advanced)\\b', 'road'],
      ['\\b(revolt|tcx)\\b', 'gravel'],
      ['\\b(roam|escape|fastroad|toughroad|cypress|rapid)\\b', 'cross'],
    ],
  },
  {
    name: 'Liv', tier: 3, aliases: ['liv'], strict: true,
    models: [
      ['\\b(intrigue e|embolden e|vall e|tempt e)\\b', 'ebike_mtb'],
      ['\\b(pique|intrigue|embolden|hail)\\b', 'mtb_full'],
      ['\\b(tempt|obsess|bliss|vall)\\b', 'mtb_hardtail'],
      ['\\b(langma|avail|enviliv)\\b', 'road'],
      ['\\b(devote)\\b', 'gravel'],
      ['\\b(alight|rove|thrive|flourish)\\b', 'cross'],
    ],
  },
  {
    name: 'Scott', tier: 4, aliases: ['scott', 'scot'],
    models: [
      ['\\b(patron|ransom eride|genius eride|strike eride|lumen eride|voltage eride|contessa strike|e spark)\\b', 'ebike_mtb_full'],
      ['\\b(aspect eride|scale eride|e scale|contessa active eride)\\b', 'ebike_mtb'],
      ['\\b(sub cross eride|e sub|axis eride|e axis|sub tour eride|sub sport eride)\\b', 'ebike_trekking'],
      ['\\b(addict eride|solace eride)\\b', 'ebike_road'],
      ['\\b(roxter|scale rc jr|scale jr|voltage jr|spark jr|contessa jr|scale 24|scale 20|voltage)\\b', 'kids'],
      ['\\b(addict gravel|speedster gravel|speedster cx|addict cx)\\b', 'gravel'],
      ['\\b(spark|genius|ransom|gambler|lumen|contessa spark|contessa genius)\\b', 'mtb_full'],
      ['\\b(scale|aspect|contessa|ratio|yecora)\\b', 'mtb_hardtail'],
      ['\\b(addict|foil|speedster|plasma|solace|cr1)\\b', 'road'],
      ['\\b(sub cross|sub sport|sub|silence|metrix)\\b', 'cross'],
    ],
  },
  {
    name: 'Cannondale', tier: 4, aliases: ['cannondale', 'canondale', 'cannondalle', 'cannondal', 'canondal', 'cannnondale'],
    models: [
      ['\\b(moterra|habit neo)\\b', 'ebike_mtb_full'],
      ['\\b(trail neo|trail neo s)\\b', 'ebike_mtb'],
      ['\\b(tesoro neo|quick neo|canvas neo|adventure neo|mavaro)\\b', 'ebike_trekking'],
      ['\\b(synapse neo|topstone neo|supersix neo)\\b', 'ebike_road'],
      ['\\b(scalpel ht)\\b', 'mtb_hardtail'],
      ['\\b(habit|jekyll|scalpel|trigger|claymore|rize|rush|prophet|moto|gemini|perp)\\b', 'mtb_full'],
      ['\\b(trail|f si|fsi|cujo|catalyst|beast of the east|chase|flash|f series)\\b', 'mtb_hardtail'],
      ['\\b(supersix|caad|synapse|systemsix|slice|lab71|r600|r800|six13)\\b', 'road'],
      ['\\b(topstone|super x|superx|slate)\\b', 'gravel'],
      ['\\b(quick|tesoro|treadwell|bad boy|badboy|adventure|hooligan)\\b', 'cross'],
    ],
  },
  {
    name: 'Santa Cruz', tier: 5, aliases: ['santa cruz', 'santacruz', 'santa cruise', 'santa cruze', 'stanta cruz'],
    models: [
      ['\\b(heckler|bullit|vala)\\b', 'ebike_mtb_full'],
      ['\\b(chameleon|highball|jackal)\\b', 'mtb_hardtail'],
      ['\\bstigmata\\b', 'gravel'],
      ['\\b(nomad|bronson|hightower|megatower|5010|tallboy|blur|v10|syndicate|superlight|heckler|butcher|nickel|juliana)\\b', 'mtb_full'],
    ],
  },
  {
    name: 'Canyon', tier: 4, aliases: ['canyon', 'canyion', 'kanyon'],
    models: [
      ['\\b(spectral on|neuron on|torque on|strive on|spectral cf on)\\b', 'ebike_mtb_full'],
      ['\\b(grand canyon on)\\b', 'ebike_mtb'],
      ['\\b(pathlite on|commuter on|roadlite on|precede on)\\b', 'ebike_trekking'],
      ['\\b(endurace on|grail on)\\b', 'ebike_road'],
      ['\\b(spectral|strive|neuron|lux|torque|sender|nerve|lux trail)\\b', 'mtb_full'],
      ['\\b(stitched|dude)\\b', 'dirt'],
      ['\\b(exceed|grand canyon|stoic|yellowstone)\\b', 'mtb_hardtail'],
      ['\\b(grail|grizl|inflite)\\b', 'gravel'],
      ['\\b(ultimate|aeroad|endurace|speedmax)\\b', 'road'],
      ['\\b(pathlite|roadlite|commuter|precede)\\b', 'cross'],
      ['\\b(offspring)\\b', 'kids'],
    ],
  },
  {
    name: 'Cube', tier: 3, aliases: ['cube', 'kube', 'qube'],
    models: [
      ['\\b(stereo hybrid|ams hybrid|stereo one22 hybrid)\\b', 'ebike_mtb_full'],
      ['\\b(reaction hybrid|acid hybrid|elite hybrid)\\b', 'ebike_mtb'],
      ['\\b(nuroad hybrid|agree hybrid)\\b', 'ebike_road'],
      ['\\b(kathmandu hybrid|touring hybrid|nuride hybrid|nature hybrid|supreme hybrid|town hybrid|compact hybrid|ella hybrid|elly ride hybrid|cross hybrid|ella ride hybrid|longtail hybrid|travel hybrid|hybrid)\\b', 'ebike_trekking'],
      ['\\b(cubie|acid 160|acid 200|acid 240|kid 160|kid 200|kid 240|cube 160|cube 200|cube 240|access 240|aim 240|aim 200|numove)\\b', 'kids'],
      ['\\b(stereo|ams|two15|one44|one55|one77|tmc|fritzz|hanzz)\\b', 'mtb_full'],
      ['\\bflying circus\\b', 'dirt'],
      ['\\b(cross race)\\b', 'cyclocross'],
      ['\\b(nuroad|gravel)\\b', 'gravel'],
      ['\\b(aim|attention|analog|reaction|ltd|elite|access|acid|phenix)\\b', 'mtb_hardtail'],
      ['\\b(attain|agree|litening|axial|aerium|peloton)\\b', 'road'],
      ['\\b(kathmandu|travel|touring|nature|nuride|sl road|hyde|editor|ella|cross)\\b', 'trekking'],
    ],
  },
  {
    name: 'Ghost', tier: 3, aliases: ['ghost', 'ghoust'],
    models: [
      ['\\b(e riot|e asx|asx|e teru|e path asx|path asx|e lector|riot am|e amr)\\b', 'ebike_mtb_full'],
      ['\\b(e kato|e lanao|e teru|hybride|e square|e hybride)\\b', 'ebike_mtb'],
      ['\\b(powerkid|kato 20|kato 24|lanao 24|lanao 20|kato kid|lanao kid|kato r1 24)\\b', 'kids'],
      ['\\b(riot|slamr|path riot|lector fs|nirvana tour fs|amr|kato fs|sl amr|polymer|cagua|cagua 2)\\b', 'mtb_full'],
      ['\\b(kato|lanao|lector|nirvana|tacana|se|lawu|powerkid)\\b', 'mtb_hardtail'],
      ['\\b(asket|road rage|fire road rage|endless road rage)\\b', 'gravel'],
      ['\\b(nivolet|race)\\b', 'road'],
      ['\\b(square|panamao|crossride|tacana)\\b', 'trekking'],
    ],
  },
  {
    name: 'Merida', tier: 3, aliases: ['merida', 'merrida', 'meridia'],
    models: [
      ['\\b(eone sixty|eone forty|eone twenty|eone|eone ninety|e one sixty|e one forty)\\b', 'ebike_mtb_full'],
      ['\\b(ebig nine|ebig seven|ebig trail|ebig|e big nine)\\b', 'ebike_mtb'],
      ['\\b(espresso|espeeder|ecross|ebig tour|e spresso)\\b', 'ebike_trekking'],
      ['\\b(esilex|escultura)\\b', 'ebike_road'],
      ['\\b(matts j|dakar|matts j 20|matts j 24|ninety six j|big nine j|chica)\\b', 'kids'],
      ['\\b(one twenty|one forty|one sixty|one ninety|ninety six|ninety six rc|one fifty|one twenty)\\b', 'mtb_full'],
      ['\\b(big nine|big seven|big trail|bigseven|bignine|matts|juliet|crossway? 29)\\b', 'mtb_hardtail'],
      ['\\b(silex|mission cx|mission)\\b', 'gravel'],
      ['\\b(scultura|reacto|ride|warp|time warp)\\b', 'road'],
      ['\\b(crossway|speeder|freeway|cross way)\\b', 'cross'],
    ],
  },
  {
    name: 'KTM', tier: 3, aliases: ['ktm'],
    models: [
      ['\\b(macina kapoho|macina prowler|macina lycan|macina chacana|macina scarp|kapoho)\\b', 'ebike_mtb_full'],
      ['\\b(macina race|macina team|macina action|macina myroon|macina ultra|macina force)\\b', 'ebike_mtb'],
      ['\\b(macina|e race)\\b', 'ebike_trekking'],
      ['\\b(wild cross|wild speed|wild one|wild buddy|wild rider)\\b', 'kids'],
      ['\\b(scarp|prowler|lycan|kapoho)\\b', 'mtb_full'],
      ['\\b(myroon|ultra|chicago|penny lane|aera|race|peak|ultra sport)\\b', 'mtb_hardtail'],
      ['\\b(x strada|canic)\\b', 'gravel'],
      ['\\b(revelator|strada|garda)\\b', 'road'],
      ['\\b(life|veneto|avenza|tourrista|life track|life ride)\\b', 'trekking'],
    ],
  },
  {
    name: 'Haibike', tier: 4, aliases: ['haibike', 'hai bike', 'haibik', 'haybike'], kind: 'ebike',
    models: [
      ['\\b(allmtn|all mtn|nduro|fullseven|fullnine|full seven|full nine|lyke|hybe|alltrail|all trail|xduro allmtn|sduro fullseven|sduro fullnine|sduro full)\\b', 'ebike_mtb_full'],
      ['\\b(hardseven|hardnine|hard seven|hard nine|alltrack|all track|hardlife|hard life|sduro hard)\\b', 'ebike_mtb'],
      ['\\b(trekking|cross|adventr)\\b', 'ebike_trekking'],
      ['\\b(urban|cityfun|city)\\b', 'ebike_city'],
    ],
  },
  {
    name: 'Focus', tier: 4, aliases: ['focus'], strict: true,
    models: [
      ['\\b(jam2|jam 2|thron2|thron 2|sam2|sam 2|vam2|vam 2)\\b', 'ebike_mtb_full'],
      ['\\b(jarifa2|jarifa 2|jarifa|bold2|bold 2|raven2|raven 2)\\b', 'ebike_mtb'],
      ['\\b(aventura2|aventura 2|planet2|planet 2|aventura)\\b', 'ebike_trekking'],
      ['\\b(paralane2|paralane 2|atlas2|atlas 2)\\b', 'ebike_road'],
      ['\\b(jam|sam|thron|o1e|spine)\\b', 'mtb_full'],
      ['\\b(raven|whistler|black forest|blackforest|bold)\\b', 'mtb_hardtail'],
      ['\\b(atlas|mares)\\b', 'gravel'],
      ['\\b(izalco|paralane|cayo|culebro|variado)\\b', 'road'],
      ['\\b(arriba|crater lake|planet)\\b', 'trekking'],
    ],
  },
  {
    name: 'Orbea', tier: 4, aliases: ['orbea', 'orbeia', 'orbia'],
    models: [
      ['\\b(wild|rise)\\b', 'ebike_mtb_full'],
      ['\\b(urrun)\\b', 'ebike_mtb'],
      ['\\b(kemen|keram|diem)\\b', 'ebike_trekking'],
      ['\\b(vibe|optima e)\\b', 'ebike_city'],
      ['\\b(gain)\\b', 'ebike_road'],
      ['\\b(occam|oiz|rallon|laufey h)\\b', 'mtb_full'],
      ['\\b(alma|mx|onna|laufey)\\b', 'mtb_hardtail'],
      ['\\b(terra)\\b', 'gravel'],
      ['\\b(orca|avant|ordu|orca aero)\\b', 'road'],
      ['\\b(carpe|vector|comfort)\\b', 'cross'],
    ],
  },
  {
    name: 'Lapierre', tier: 4, aliases: ['lapierre', 'lapiere', 'la pierre'],
    models: [
      ['\\b(overvolt am|overvolt glp|overvolt tr|ezesty|e zesty|overvolt)\\b', 'ebike_mtb_full'],
      ['\\b(overvolt ht)\\b', 'ebike_mtb'],
      ['\\b(spicy|zesty|xr|xrm|froggy|dh)\\b', 'mtb_full'],
      ['\\b(edge|prorace|raid)\\b', 'mtb_hardtail'],
      ['\\b(crosshill)\\b', 'gravel'],
      ['\\b(xelius|pulsium|aircode|sensium|audacio)\\b', 'road'],
      ['\\b(trekking|shaper)\\b', 'trekking'],
    ],
  },
  {
    name: 'Kona', tier: 4, aliases: ['kona'], strict: true,
    models: [
      ['\\b(remote)\\b', 'ebike_mtb_full'],
      ['\\b(process|hei hei|stinky|operator|satori|coiler|entourage|abra cadabra)\\b', 'mtb_full'],
      ['\\b(honzo|mahuna|lana i|lanai|fire mountain|blast|cinder cone|big honzo|kahuna|unit|explosif)\\b', 'mtb_hardtail'],
      ['\\b(rove|sutra|libre|jake|major jake|private jake)\\b', 'gravel'],
      ['\\b(shonky|cowan)\\b', 'dirt'],
      ['\\b(dew|coco)\\b', 'city'],
    ],
  },
  {
    name: 'Marin', tier: 3, aliases: ['marin'], strict: true,
    models: [
      ['\\b(rift zone|alpine trail|hawk hill|mount vision|el roy|attack trail|b17)\\b', 'mtb_full'],
      ['\\b(bayview|donky jr|hidden canyon)\\b', 'kids'],
      ['\\b(bobcat trail|wildcat|san quentin|nail trail|palisades|pine mountain|bolinas ridge|eldridge|team marin)\\b', 'mtb_hardtail'],
      ['\\b(gestalt|four corners|headlands|nicasio|lombard|dsx)\\b', 'gravel'],
      ['\\b(fairfax|kentfield|larkspur|muirwoods|presidio|stinson|san rafael|terra linda)\\b', 'cross'],
    ],
  },
  {
    name: 'GT', tier: 3, aliases: ['gt', 'gt bikes', 'gtbikes'],
    models: [
      ['\\b(ebump|e force|e verb)\\b', 'ebike_mtb'],
      ['\\b(stomper)\\b', 'kids'],
      ['\\b(sensor|force|fury|distortion|helion|zaskar lt|zaskar fs|sanction|i drive|idrive|lts|xcr)\\b', 'mtb_full'],
      ['\\b(performer|compe|pro series|slammer|mach one|bump|power series|air|team comp|interceptor|heritage|speed series|fly|vertigo|dyno)\\b', 'bmx'],
      ['\\b(labomba|la bomba|chucker)\\b', 'dirt'],
      ['\\b(avalanche|aggressor|zaskar|pantera|karakoram|timberline|palomar|verb|laguna|outpost|tequesta|richter)\\b', 'mtb_hardtail'],
      ['\\b(grade)\\b', 'gravel'],
      ['\\b(gtr|edge|strike|zr)\\b', 'road'],
      ['\\b(transeo|traffic|nomad)\\b', 'cross'],
    ],
  },
  {
    name: 'BMC', tier: 4, aliases: ['bmc'],
    models: [
      ['\\b(amp|speedfox amp|trailfox amp|fourstroke amp)\\b', 'ebike_mtb_full'],
      ['\\b(fourstroke|speedfox|trailfox|agonist)\\b', 'mtb_full'],
      ['\\b(twostroke|sportelite|teamelite)\\b', 'mtb_hardtail'],
      ['\\b(urs|unrestricted|kaius|crossmachine)\\b', 'gravel'],
      ['\\b(teammachine|roadmachine|timemachine|slr|alr|granfondo|streetfire)\\b', 'road'],
      ['\\b(alpenchallenge)\\b', 'cross'],
    ],
  },
  {
    name: 'Bianchi', tier: 4, aliases: ['bianchi', 'bianci', 'bianki', 'biachi'],
    models: [
      ['\\b(e omnia|t tronik|e vertic|aria e road|impulso e road|e road)\\b', 'ebike_road'],
      ['\\b(arcadex|impulso allroad|zolder)\\b', 'gravel'],
      ['\\b(methanol fs)\\b', 'mtb_full'],
      ['\\b(methanol|magma|nitron|jab|kuma)\\b', 'mtb_hardtail'],
      ['\\b(oltre|specialissima|sprint|infinito|aria|intenso|via nirone|nirone|sempre|impulso|vertigo|xr4|xr3|xr2|sport)\\b', 'road'],
    ],
  },
  { name: 'Pinarello', tier: 5, aliases: ['pinarello', 'pinarelo', 'pinnarello'], kind: 'road', models: [['\\bgrevil\\b', 'gravel'], ['\\b(dyodo|nytro)\\b', 'ebike_road']] },
  { name: 'Colnago', tier: 5, aliases: ['colnago', 'colnaco', 'colnagho'], kind: 'road', models: [['\\b(g3 x|g3x)\\b', 'gravel'], ['\\be64\\b', 'ebike_road']] },
  { name: 'Cervélo', tier: 5, aliases: ['cervelo', 'cervello', 'cervélo'], kind: 'road', models: [['\\baspero\\b', 'gravel'], ['\\bzht\\b', 'mtb_full']] },
  { name: 'Wilier', tier: 4, aliases: ['wilier', 'willier', 'wilier triestina', 'villier'], kind: 'road', models: [['\\b(rave|jena|jareen|adlar)\\b', 'gravel'], ['\\b(urta|110x|101x|503x)\\b', 'mtb_hardtail']] },
  { name: 'Ridley', tier: 4, aliases: ['ridley', 'ridly'], kind: 'road', models: [['\\b(kanzo|x night|x ride|x trail|astr)\\b', 'gravel']] },
  {
    name: 'Rose', tier: 4, aliases: ['rose'], strict: true,
    models: [
      ['\\b(root miller|granite chief|thrill hill|soul fire|ground control|uncle jimbo|pikes peak|beef cake)\\b', 'mtb_full'],
      ['\\b(psycho path|count solo|bonero|crown jewel)\\b', 'mtb_hardtail'],
      ['\\b(backroad|hobo)\\b', 'gravel'],
      ['\\b(xlite|x lite|reveal|pro sl|xeon|team gf)\\b', 'road'],
    ],
  },
  {
    name: 'Radon', tier: 3, aliases: ['radon'],
    models: [
      ['\\b(render hybrid|jab hybrid|swoop hybrid|skeen hybrid|deft)\\b', 'ebike_mtb_full'],
      ['\\b(zr team hybrid|jealous hybrid)\\b', 'ebike_mtb'],
      ['\\b(slide|skeen|swoop|jab|render|stage)\\b', 'mtb_full'],
      ['\\b(jealous|zr team|zr race|cragger)\\b', 'mtb_hardtail'],
      ['\\b(regard|spire|vaillant|r1|sprinter)\\b', 'road'],
    ],
  },
  { name: 'YT', tier: 4, aliases: ['yt', 'yt industries', 'ytindustries'], models: [['\\b(decoy)\\b', 'ebike_mtb_full'], ['\\b(dirt love|play)\\b', 'dirt'], ['\\b(jeffsy|capra|izzo|tues|szepter)\\b', 'mtb_full']] },
  {
    name: 'Commencal', tier: 4, aliases: ['commencal', 'comencal', 'commencall', 'commençal', 'commecal'],
    models: [
      ['\\b(meta power|meta power sx)\\b', 'ebike_mtb_full'],
      ['\\b(absolut|ramones)\\b', 'dirt'],
      ['\\b(meta ht|el camino)\\b', 'mtb_hardtail'],
      ['\\b(meta|supreme|clash|furious|tempo|fcs)\\b', 'mtb_full'],
    ],
  },
  { name: 'Nukeproof', tier: 4, aliases: ['nukeproof', 'nuke proof'], models: [['\\bmegawatt\\b', 'ebike_mtb_full'], ['\\bscout\\b', 'mtb_hardtail'], ['\\bdigger\\b', 'gravel'], ['\\b(mega|giga|reactor|dissent|pulse)\\b', 'mtb_full']] },
  { name: 'Transition', tier: 4, aliases: ['transition'], strict: true, models: [['\\b(repeater|relay)\\b', 'ebike_mtb_full'], ['\\b(pbj)\\b', 'dirt'], ['\\b(sentinel|patrol|spire|scout|smuggler|tr11|tr 11|spur|covert|bandit|tr450|tr 450)\\b', 'mtb_full']] },
  { name: 'Pivot', tier: 5, aliases: ['pivot'], strict: true, models: [['\\bshuttle\\b', 'ebike_mtb_full'], ['\\bvault\\b', 'gravel'], ['\\bles\\b', 'mtb_hardtail'], ['\\b(mach|firebird|switchblade|trail 429|shadowcat|phoenix)\\b', 'mtb_full']] },
  { name: 'Yeti', tier: 5, aliases: ['yeti'], models: [['\\b(160e|mtx)\\b', 'ebike_mtb_full'], ['\\barc\\b', 'mtb_hardtail'], ['\\b(sb\\d+|sb \\d+|asr|sb)\\b', 'mtb_full']] },
  {
    name: 'Norco', tier: 4, aliases: ['norco'],
    models: [
      ['\\b(sight vlt|range vlt|fluid vlt|vlt)\\b', 'ebike_mtb_full'],
      ['\\b(sight|range|optic|fluid fs|aurum|revolver|shore)\\b', 'mtb_full'],
      ['\\b(torrent|charger|storm|fluid ht|fluid)\\b', 'mtb_hardtail'],
      ['\\b(search|section|threshold)\\b', 'gravel'],
      ['\\b(indie|scene)\\b', 'cross'],
    ],
  },
  {
    name: 'Rocky Mountain', tier: 4, aliases: ['rocky mountain', 'rockymountain', 'rocky mountains'],
    models: [
      ['\\b(powerplay|altitude powerplay|instinct powerplay|fusion powerplay)\\b', 'ebike_mtb_full'],
      ['\\b(altitude|instinct|element|slayer|thunderbolt|reaper|pipeline|maiden)\\b', 'mtb_full'],
      ['\\b(growler|fusion|vertex|soul|flow|blizzard)\\b', 'mtb_hardtail'],
      ['\\bsolo\\b', 'gravel'],
    ],
  },
  {
    name: 'Polygon', tier: 2, aliases: ['polygon'],
    models: [
      ['\\b(siskiu|collosus|entiat|square one)\\b', 'mtb_full'],
      ['\\b(xtrada|cascade|premier|monarch|syncline)\\b', 'mtb_hardtail'],
      ['\\b(strattos|helios)\\b', 'road'],
      ['\\b(bend|path)\\b', 'gravel'],
    ],
  },
  { name: 'Propain', tier: 4, aliases: ['propain', 'pro pain'], models: [['\\bekano\\b', 'ebike_mtb_full'], ['\\b(tyee|spindrift|hugene|twoface|rage|sresh|spindrift cf)\\b', 'mtb_full']] },
  {
    name: 'Mondraker', tier: 4, aliases: ['mondraker', 'mondracker', 'mondrakker', 'mondrejker'],
    models: [
      ['\\b(crafty|level|dusk|neat|sly|e summum)\\b', 'ebike_mtb_full'],
      ['\\b(prime|chaser|thundra|e prime)\\b', 'ebike_mtb'],
      ['\\b(foxy|raze|superfoxy|summum|f podium|dune|factor|vantage|mr)\\b', 'mtb_full'],
      ['\\b(chrono|podium|leader|phase)\\b', 'mtb_hardtail'],
    ],
  },
  { name: 'Ibis', tier: 5, aliases: ['ibis'], models: [['\\b(oso)\\b', 'ebike_mtb_full'], ['\\b(dv9)\\b', 'mtb_hardtail'], ['\\b(hakka)\\b', 'gravel'], ['\\b(ripmo|ripley|mojo|exie)\\b', 'mtb_full']] },
  { name: 'Evil', tier: 5, aliases: ['evil'], strict: true, models: [['\\b(chamois hagar)\\b', 'gravel'], ['\\b(following|offering|wreckoning|insurgent|calling)\\b', 'mtb_full']] },
  { name: 'Intense', tier: 4, aliases: ['intense'], strict: true, models: [['\\b(tracer|primer|carbine|sniper|m29|m16|uzzi|spider)\\b', 'mtb_full']] },
  { name: 'Devinci', tier: 4, aliases: ['devinci'], models: [['\\b(troy|spartan|marshall|django|wilson)\\b', 'mtb_full']] },
  { name: 'Forbidden', tier: 5, aliases: ['forbidden'], strict: true, models: [['\\b(druid|dreadnought)\\b', 'mtb_full']] },
  { name: 'Niner', tier: 4, aliases: ['niner'], models: [['\\b(rlt|mcr)\\b', 'gravel'], ['\\b(air 9|sir 9|emd)\\b', 'mtb_hardtail'], ['\\b(rip 9|rkt|jet 9|wfo)\\b', 'mtb_full']] },
  { name: 'Salsa', tier: 4, aliases: ['salsa'], strict: true, models: [['\\b(warbird|cutthroat|journeyman|fargo|vaya|stormchaser)\\b', 'gravel'], ['\\b(mukluk|beargrease)\\b', 'fatbike']] },
  { name: 'Surly', tier: 4, aliases: ['surly'], models: [['\\b(pugsley|wednesday|ice cream truck|moonlander)\\b', 'fatbike'], ['\\b(cross check|straggler|midnight special|disc trucker|long haul trucker|bridge club)\\b', 'gravel']] },
  { name: 'Felt', tier: 4, aliases: ['felt'], strict: true, models: [['\\b(breed|broam)\\b', 'gravel'], ['\\b(compulsion|decree|doctrine|edict|surplus)\\b', 'mtb_full'], ['\\b(fr|ar|ia|vr|f\\d+|z\\d+)\\b', 'road']] },
  { name: 'Fuji', tier: 3, aliases: ['fuji'], models: [['\\bjari\\b', 'gravel'], ['\\b(nevada|tahoe|auric|reveal)\\b', 'mtb_hardtail'], ['\\b(sl|transonic|norcom|sportif|gran fondo|roubaix)\\b', 'road']] },
  { name: 'Cinelli', tier: 4, aliases: ['cinelli', 'cineli'], models: [['\\b(nemo|hobootleg|zydeco|king zydeco)\\b', 'gravel'], ['\\b(vigorelli|gazzetta|tutto|mash)\\b', 'city']], kind: 'road' },
  { name: 'Look', tier: 4, aliases: ['look'], strict: true, kind: 'road' },
  { name: 'Time', tier: 4, aliases: ['time'], strict: true, kind: 'road' },
  { name: 'Factor', tier: 5, aliases: ['factor'], strict: true, kind: 'road' },
  { name: 'Basso', tier: 4, aliases: ['basso'], kind: 'road' },
  { name: 'De Rosa', tier: 5, aliases: ['de rosa', 'derosa'], kind: 'road' },
  { name: 'Argon 18', tier: 4, aliases: ['argon 18', 'argon18'], kind: 'road' },
  { name: '3T', tier: 4, aliases: ['3t'], models: [['\\b(exploro|racemax|extrema)\\b', 'gravel']], kind: 'road' },
  { name: 'Open', tier: 5, aliases: ['open cycle', 'opencycle', 'open u p', 'open wi de', 'open up'], models: [['.', 'gravel']] },
  { name: 'Eddy Merckx', tier: 4, aliases: ['eddy merckx', 'merckx'], kind: 'road' },
  { name: 'Gianni Motta', tier: 3, aliases: ['gianni motta'], kind: 'road' },
  { name: 'McKenzie', tier: 1, aliases: ['mckenzie', 'mc kenzie'] },
  { name: 'Madison', tier: 1, aliases: ['madison'], strict: true },
  { name: 'Duratec', tier: 2, aliases: ['duratec'] },
  { name: 'Storck', tier: 4, aliases: ['storck'], kind: 'road' },
  { name: 'Cipollini', tier: 4, aliases: ['cipollini'], kind: 'road' },
  { name: 'Kuota', tier: 3, aliases: ['kuota'], kind: 'road' },
  { name: 'Officine Mattio', tier: 5, aliases: ['officine mattio', 'mattio'], kind: 'road' },
  { name: 'Quintana Roo', tier: 4, aliases: ['quintana roo', 'quintanaroo'], kind: 'road' },
  { name: 'Stevens', tier: 3, aliases: ['stevens'], strict: true, models: [['\\b(e whistler|e sledge|e inception|e pordoi|e triton|e lavena)\\b', 'ebike_mtb'], ['\\b(whistler|sonora|applebee|jura|devil s trail)\\b', 'mtb_hardtail'], ['\\b(sledge|inception|jumper|whaka)\\b', 'mtb_full'], ['\\b(prestige|super prestige|vapor|gavere)\\b', 'cyclocross'], ['\\b(comet|aspin|izoard|xenith|arcalis|stelvio|san remo|ventoux|vuelta)\\b', 'road'], ['\\b(camino|gavere|tremalzo|p18)\\b', 'gravel']] },
  { name: 'Conway', tier: 3, aliases: ['conway'], models: [['\\b(xyron|cairon|ewme|wme e|ryvon|e wme)\\b', 'ebike_mtb'], ['\\b(wme|mf|wmt)\\b', 'mtb_full'], ['\\b(ms|mlt|mc)\\b', 'mtb_hardtail'], ['\\b(gr|grv)\\b', 'gravel']] },
  { name: 'Corratec', tier: 3, aliases: ['corratec', 'coratec', 'coratech'], models: [['\\b(e power|epower|e bow|ebow)\\b', 'ebike_mtb'], ['\\b(x vert|xvert|revolution|superbow)\\b', 'mtb_hardtail'], ['\\b(inside link|il)\\b', 'mtb_full'], ['\\b(corones|allroad|dolomiti|ccr|ccx)\\b', 'road']] },
  { name: 'Bergamont', tier: 3, aliases: ['bergamont', 'bergamond'], models: [['\\b(e trailster|e contrail|e revox|e horizon|e ville|e sweep|e helix)\\b', 'ebike_mtb'], ['\\b(trailster|contrail|encore|straitline)\\b', 'mtb_full'], ['\\b(revox|roxtar|fastlane)\\b', 'mtb_hardtail'], ['\\b(grandurance|prime)\\b', 'gravel'], ['\\b(helix|horizon|sweep|vitess)\\b', 'trekking']] },
  { name: 'Centurion', tier: 3, aliases: ['centurion'], models: [['\\b(no pogo|lhasa e)\\b', 'ebike_mtb_full'], ['\\b(backfire|lhasa)\\b', 'mtb_hardtail'], ['\\b(crossline|cross line|city speed)\\b', 'trekking']] },
  { name: 'Simplon', tier: 4, aliases: ['simplon'], models: [['\\b(rapcon pmax|steamer pmax|sengo pmax|chenoa|kagu)\\b', 'ebike_mtb_full'], ['\\b(rapcon|steamer|stomp)\\b', 'mtb_full'], ['\\b(pride|inissio|nexio)\\b', 'road']] },
  { name: 'Rotwild', tier: 5, aliases: ['rotwild'], models: [['\\b(r x375|r e375|r x750|r e750|r x1|r e1|r g1)\\b', 'ebike_mtb_full'], ['.', 'mtb_full']] },
  { name: 'Whyte', tier: 4, aliases: ['whyte'], models: [['\\b(e 160|e 150|e 180|e 106|e 506|e 405)\\b', 'ebike_mtb_full'], ['\\b(t 130|t 140|g 180|s 150|t 160|g 170|s 120)\\b', 'mtb_full'], ['\\b(909|905|901|802|806|801|529|629|405)\\b', 'mtb_hardtail']] },
  { name: 'Orange', tier: 4, aliases: ['orange'], strict: true, models: [['\\b(phase|surge)\\b', 'ebike_mtb_full'], ['\\b(five|stage|alpine|segment|four|switch|327|224|patriot)\\b', 'mtb_full'], ['\\b(crush|clockwork|p7|zest|prime)\\b', 'mtb_hardtail']] },
  { name: 'Vitus', tier: 3, aliases: ['vitus'], models: [['\\b(e sommet|e mythique|e escarpe)\\b', 'ebike_mtb_full'], ['\\b(sommet|escarpe|mythique)\\b', 'mtb_full'], ['\\b(sentier|nucleus)\\b', 'mtb_hardtail'], ['\\b(substance|energie)\\b', 'gravel'], ['\\b(vitesse|zenium|razor)\\b', 'road']] },
  { name: 'Saracen', tier: 3, aliases: ['saracen'], models: [['\\b(myst|ariel|kili)\\b', 'mtb_full'], ['\\b(mantra|tufftrax|zenith)\\b', 'mtb_hardtail']] },
  { name: 'Boardman', tier: 3, aliases: ['boardman'], kind: 'road' },
  { name: 'Unno', tier: 5, aliases: ['unno'], models: [['.', 'mtb_full']] },
  { name: 'Atherton', tier: 5, aliases: ['atherton'], models: [['.', 'mtb_full']] },
  { name: 'Banshee', tier: 4, aliases: ['banshee'], models: [['.', 'mtb_full']] },

  // --- e-kola (střední / prémiové) ---
  {
    name: 'Bulls', tier: 3, aliases: ['bulls', 'bull s'],
    models: [
      ['\\b(sonic am|sonic evo am|e stream evo am|e stream am|wild flow|copperhead evo am|sonic evo ex|sonic evo)\\b', 'ebike_mtb_full'],
      ['\\b(copperhead evo|e stream evo|aminga|sonic evo ht|iconic evo)\\b', 'ebike_mtb'],
      ['\\b(lacuba|cross lite|iconic|cross mover|outlaw evo|green mover|urban)\\b', 'ebike_trekking'],
      ['\\b(copperhead|wildtail|wild edge|king bull)\\b', 'mtb_hardtail'],
      ['\\b(harrier|desert falcon)\\b', 'road'],
    ],
  },
  { name: 'Moustache', tier: 5, aliases: ['moustache', 'mustache'], kind: 'ebike', models: [['\\b(trail|game)\\b', 'ebike_mtb_full'], ['\\b(lundi|j|friday)\\b', 'ebike_city'], ['.', 'ebike_trekking']] },
  { name: 'Riese & Müller', tier: 5, aliases: ['riese muller', 'riese und muller', 'riese mueller', 'riese', 'r m load', 'r m nevo', 'r m charger'], kind: 'ebike', models: [['\\b(load|packster|multicharger|transporter|carrie|multitinker)\\b', 'ebike_cargo'], ['\\b(tinker|culture|homage)\\b', 'ebike_city'], ['.', 'ebike_trekking']] },
  { name: 'Kalkhoff', tier: 3, aliases: ['kalkhoff', 'kalkof', 'kalkhof'], models: [['\\b(entice)\\b', 'ebike_mtb'], ['\\b(endeavour|image|agattu|berleen|integrale|include)\\b', 'ebike_trekking']] },
  { name: 'Winora', tier: 3, aliases: ['winora'], models: [['\\b(sinus|yucatan|yakun|tria|radar|f1|y280|y420)\\b', 'ebike_trekking']] },
  { name: 'Flyer', tier: 4, aliases: ['flyer'], strict: true, kind: 'ebike', models: [['\\b(uproc)\\b', 'ebike_mtb_full'], ['\\b(upstreet|gotour|goa|tenero)\\b', 'ebike_trekking']] },
  { name: 'Gazelle', tier: 3, aliases: ['gazelle', 'gazela'], strict: true, models: [['\\b(ultimate|arroyo|grenoble|paris|esprit|heavy duty|miss grace|cityzen|eclipse|orange|chamonix|medeo)\\b', 'city']] },
  { name: 'Raymon', tier: 3, aliases: ['raymon', 'raymond'], models: [['\\b(norza|korai)\\b', 'ebike_road'], ['\\b(fullray|trailray|airray|e seven)\\b', 'ebike_mtb_full'], ['\\b(hardray|yamaray|tahona)\\b', 'ebike_mtb'], ['\\b(crossray|tourray)\\b', 'ebike_trekking'], ['\\b(cityray)\\b', 'ebike_city'], ['\\b(nineray|sevenray)\\b', 'mtb_hardtail'], ['\\b(trailray)\\b', 'mtb_full']] },
  { name: 'Husqvarna', tier: 4, aliases: ['husqvarna', 'husquarna', 'husqvarnu', 'husqwarna'], kind: 'ebike', models: [['\\b(mc|ec|lc|mountain cross|light cross|extreme cross|hard cross 8|mc\\d|ec\\d|lc\\d)\\b', 'ebike_mtb_full'], ['\\b(hc|hard cross|hc\\d)\\b', 'ebike_mtb'], ['\\b(gran|gt|ct|cross tourer|pather|grand tourer|gu|gc)\\b', 'ebike_trekking']] },
  { name: 'Pells', tier: 2, aliases: ['pells', 'pels'], models: [['\\b(e razzer|razzer e|e smasher|e racer)\\b', 'ebike_mtb'], ['\\b(razzer|smasher|xc|rexi)\\b', 'mtb_hardtail'], ['\\b(crono|cuttie|cutie)\\b', 'cross']] },
  { name: 'Ecobike', tier: 2, aliases: ['ecobike', 'eco bike', 'ekobike'], kind: 'ebike', models: [['\\b(sx|sx \\d+|rs)\\b', 'ebike_mtb'], ['\\b(traffic|basic|cortina|city|urban|x cross|even|elite)\\b', 'ebike_city']] },
  { name: 'Crussis', tier: 2, aliases: ['crussis', 'crusis', 'cruissis', 'krusis', 'crussic', 'crusiss', 'krussis', 'crussi'], kind: 'ebike', models: [['\\b(e full|efull|full)\\b', 'ebike_mtb_full'], ['\\b(e atland|atland|e largo|largo|e gordo|gordo|guera|one guera|onex guera|one atland|e fat)\\b', 'ebike_mtb'], ['\\b(e cross|cross|e country|country|e savela|savela|e lady|lady|e city|famsoul|e family|e pharo|e bella|pharo|bella|e citty)\\b', 'ebike_trekking']] },
  { name: 'Apache', tier: 2, aliases: ['apache', 'apachee', 'apatche'], kind: 'ebike', models: [['\\b(gila|kanaa? gravel)\\b', 'ebike_road'], ['\\b(tuwa|kanaa|quruk|manitou|chosa|tate|ayita)\\b', 'ebike_mtb'], ['\\b(matto|wakita|hupahu|yuma|catori|kachina)\\b', 'ebike_mtb'], ['\\b(sarai|bajada|tasha|yanta|naira)\\b', 'ebike_trekking']] },
  { name: 'Lovelec', tier: 2, aliases: ['lovelec', 'love lec'], kind: 'ebike' },
  { name: 'Agogs', tier: 2, aliases: ['agogs', 'agog s'], kind: 'ebike' },
  { name: 'Sobi', tier: 1, aliases: ['sobi'], strict: true },
  { name: 'MTF', tier: 1, aliases: ['mtf', 'mft'], kind: 'cheap_ebike' },
  { name: 'Himiway', tier: 1, aliases: ['himiway'], kind: 'cheap_ebike' },
  { name: 'Engwe', tier: 1, aliases: ['engwe'], kind: 'cheap_ebike' },
  { name: 'Lankeleisi', tier: 1, aliases: ['lankeleisi'], kind: 'cheap_ebike' },
  { name: 'Fiido', tier: 1, aliases: ['fiido'], kind: 'cheap_ebike' },
  { name: 'Xiaomi', tier: 1, aliases: ['xiaomi', 'himo'], kind: 'cheap_ebike' },
  { name: 'Kentoya', tier: 1, aliases: ['kentoya'], kind: 'cheap_ebike' },
  { name: 'Voltera', tier: 1, aliases: ['voltera'], kind: 'cheap_ebike' },
  { name: 'Eleglide', tier: 1, aliases: ['eleglide'], kind: 'cheap_ebike' },
  { name: 'Samebike', tier: 1, aliases: ['samebike'], kind: 'cheap_ebike' },
  { name: 'Duotts', tier: 1, aliases: ['duotts'], kind: 'cheap_ebike' },
  { name: 'ADO', tier: 1, aliases: ['ado'], strict: true, kind: 'cheap_ebike' },
  { name: 'RDX', tier: 1, aliases: ['rdx'], kind: 'cheap_ebike' },
  { name: 'Super73', tier: 3, aliases: ['super73', 'super 73'], kind: 'ebike', models: [['.', 'ebike_city']] },
  { name: 'Spirit', tier: 1, aliases: ['spirit'], strict: true },
  { name: 'Shockblaze', tier: 2, aliases: ['shockblaze', 'shock blaze'], kind: 'ebike' },
  { name: 'Dutch ID', tier: 2, aliases: ['dutch id', 'dutchid'], kind: 'ebike' },
  { name: 'Ducati', tier: 4, aliases: ['ducati'], kind: 'ebike', models: [['\\b(mig s|mig rr|tk 01|mig)\\b', 'ebike_mtb_full']] },
  { name: 'Thok', tier: 3, aliases: ['thok'], kind: 'ebike', models: [['.', 'ebike_mtb_full']] },
  { name: 'Fantic', tier: 4, aliases: ['fantic'], kind: 'ebike', models: [['.', 'ebike_mtb_full']] },
  { name: 'Bultaco', tier: 3, aliases: ['bultaco'], kind: 'ebike', models: [['.', 'ebike_mtb_full']] },
  { name: 'M1 Sporttechnik', tier: 4, aliases: ['m1 sporttechnik', 'm1 sterzing', 'm1 spitzing', 'm1 erzberg'], kind: 'ebike', models: [['.', 'ebike_mtb_full']] },
  { name: 'Leon', tier: 2, aliases: ['leon cycle'], kind: 'ebike' },

  // --- české a slovenské značky ---
  {
    name: 'Author', tier: 2, aliases: ['author', 'authror', 'auhtor', 'authora', 'aithor', 'athor', 'autor', 'authour'], strict: true,
    models: [
      ['\\b(engine|integra|a matrix|e matrix)\\b', 'ebike_mtb'],
      ['\\b(jet|cosmic|smart|stylo|orbit|bello|magic|energy|limit|agang|cyclone|gift|cocoo|floppy|neon|basic)\\b', 'kids'],
      ['\\b(ultimate|dexter|revolt)\\b', 'mtb_full'],
      ['\\b(traction|solution|spirit|sector|rival|pegas|instinct|mission|outset|impulse|vertigo|matrix)\\b', 'mtb_hardtail'],
      ['\\b(aura|ronin|charisma|aura xr)\\b', 'road'],
      ['\\b(grand|stratos|horizon|classic|ronin|crg|natur)\\b', 'trekking'],
      ['\\b(compact|record|elite|simplex|resolve)\\b', 'city'],
    ],
  },
  {
    name: 'Superior', tier: 3, aliases: ['superior', 'superiror', 'superrior', 'superios', 'superjor'],
    models: [
      ['\\b(exf|e xf|xf e)\\b', 'ebike_mtb_full'],
      ['\\b(exc|exp|e xc|e xp|ext)\\b', 'ebike_mtb'],
      ['\\b(exr|e xr)\\b', 'ebike_road'],
      ['\\b(erx|esx|e rx|e sx)\\b', 'ebike_trekking'],
      ['\\b(racer|modo|f l y|fly|xc 7\\d\\d|xc 2\\d\\d|xc 8\\d\\d? 24|xc 24|xc 20|xc 16)\\b', 'kids'],
      ['\\b(xf|team issue xf|xf 9\\d\\d)\\b', 'mtb_full'],
      ['\\b(xc|xp|team issue|team comp|xf ht)\\b', 'mtb_hardtail'],
      ['\\b(xr|x road)\\b', 'gravel'],
      ['\\b(rx|sx|rx 5\\d\\d|cobra)\\b', 'cross'],
    ],
  },
  {
    name: 'Kellys', tier: 3, aliases: ['kellys', 'kelly s', 'kelys', 'kellis', 'kelly', 'kellyss', 'kelis'],
    models: [
      ['\\b(theos|tygon r|tyon e)\\b', 'ebike_mtb_full'],
      ['\\b(tygon|tayen|hacker r|e gate|tyger)\\b', 'ebike_mtb'],
      ['\\b(estima|e carson|e cristy|e phanatic|e cristy|e clea|e carter)\\b', 'ebike_trekking'],
      ['\\b(kiter|lumi|wasper|marc|naga|cookie|caprice|pirate|lumi|kitty|blaze|rider|wasper|madman 24|spider 10|spider 20)\\b', 'kids'],
      ['\\b(whip|gear|sniper)\\b', 'dirt'],
      ['\\b(tyon|thorx|swag|slanger|tnt|eraser)\\b', 'mtb_full'],
      ['\\b(spider|gate|desert|hacker|madman|viper|vanity|mojo|zebra|spy|tnt|alpha|lock|frontrunner)\\b', 'mtb_hardtail'],
      ['\\b(soot|nebula)\\b', 'gravel'],
      ['\\b(arc|urc|pro sport)\\b', 'road'],
      ['\\b(carter|cristy|avenue|axis)\\b', 'trekking'],
      ['\\b(phanatic|cliff|physio|clea|neat)\\b', 'cross'],
    ],
  },
  {
    name: 'Rock Machine', tier: 2, aliases: ['rock machine', 'rockmachine', 'rock machina', 'rockmachina', 'rock machin', 'rock mashine'],
    models: [
      ['\\b(blizzard int e|torrent int e|blizzard int e)\\b', 'ebike_mtb_full'],
      ['\\b(blizzard e|torrent e|storm e|thunder e|blizzard e\\d|torrent e\\d|storm e\\d|xcp)\\b', 'ebike_mtb'],
      ['\\b(crossride e|cityride e|e crossride)\\b', 'ebike_trekking'],
      ['\\b(thunder|blizz|catherine|cathrine|surge|rocky|minirock|storm 24)\\b', 'kids'],
      ['\\b(blizzard int|torrent int|blizzard xcm|cheetah)\\b', 'mtb_full'],
      ['\\b(blizzard|torrent|manhattan|storm|catherine|surge|fire|tunder)\\b', 'mtb_hardtail'],
      ['\\b(gravelride)\\b', 'gravel'],
      ['\\b(crossride|cityride)\\b', 'cross'],
    ],
  },
  { name: '4ever', tier: 2, aliases: ['4ever', '4 ever', 'forever'], models: [['\\b(virtus|fever|sceed|credit|crossfire|wolf|ultra|wildcat)\\b', 'mtb_hardtail'], ['\\b(compact|rayen|beat|vista|rocker)\\b', 'trekking']] },
  { name: 'CTM', tier: 2, aliases: ['ctm'], models: [['\\b(rascal|rein e|metric e|pulze|e pulze|kiruna e)\\b', 'ebike_mtb'], ['\\b(willy|jerry|scooby|polly|marry|rocky|maggie|berry|frieda|fox|billy|molly)\\b', 'kids'], ['\\b(scroll|skyline)\\b', 'mtb_full'], ['\\b(rambler|charisma|zephyr|rein|swing|rocksteady|wire|zephyr)\\b', 'mtb_hardtail'], ['\\b(kiruna|stefi|tranz|terra|maxima|metric|olivia|elite)\\b', 'trekking']] },
  { name: 'Leader Fox', tier: 2, aliases: ['leader fox', 'leaderfox', 'lider fox', 'leadfer fox', 'leader foux', 'leder fox', 'leaedr fox'] },
  { name: 'King Fox', tier: 1, aliases: ['king fox'] },
  { name: 'Amulet', tier: 2, aliases: ['amulet'], models: [['\\b(e rival|e rival trail|eone)\\b', 'ebike_mtb'], ['\\b(tomcat|speedy|night hawk|fluffy|mysty|ellie)\\b', 'kids'], ['\\b(rival|reserve|night hawk)\\b', 'mtb_hardtail']] },
  { name: 'Olpran', tier: 1, aliases: ['olpran', 'olpram', 'olpren'], models: [['\\b(zeus)\\b', 'gravel'], ['\\b(eclipse)\\b', 'cross']] },
  { name: 'Galaxy', tier: 1, aliases: ['galaxy'], strict: true },
  { name: 'Dema', tier: 1, aliases: ['dema'] },
  { name: 'Esperia', tier: 1, aliases: ['esperia'] },
  { name: 'Maxbike', tier: 1, aliases: ['maxbike', 'max bike'] },
  { name: 'Mondial', tier: 1, aliases: ['mondial'], strict: true },
  { name: 'Sulov', tier: 1, aliases: ['sulov'] },
  { name: 'Kenzel', tier: 1, aliases: ['kenzel'] },
  { name: 'Toimsa', tier: 1, aliases: ['toimsa'] },
  { name: 'Dino Bikes', tier: 1, aliases: ['dino bikes', 'dinobikes'] },
  { name: 'Bemoov', tier: 1, aliases: ['bemoov'] },
  { name: 'Liberta', tier: 1, aliases: ['liberta'] },
  { name: 'Arcore', tier: 2, aliases: ['arcore'] },
  { name: 'Wheeler', tier: 2, aliases: ['wheeler'] },
  { name: 'Genesis', tier: 2, aliases: ['genesis'], strict: true },
  { name: 'Kross', tier: 2, aliases: ['kross'] },
  { name: 'Romet', tier: 1, aliases: ['romet'] },
  { name: 'Head', tier: 2, aliases: ['head'], strict: true },
  { name: 'MBM', tier: 1, aliases: ['mbm'] },
  { name: 'Sava', tier: 2, aliases: ['sava'], strict: true },
  { name: 'Rawo', tier: 1, aliases: ['rawo', 'ravo'] },
  { name: 'Montana', tier: 1, aliases: ['montana'], strict: true },
  { name: 'Dakota', tier: 1, aliases: ['dakota'], strict: true },
  { name: 'Steppenwolf', tier: 3, aliases: ['steppenwolf'] },
  { name: 'Gary Fisher', tier: 3, aliases: ['gary fisher', 'garry fisher', 'fisher'] },
  { name: 'Univega', tier: 2, aliases: ['univega'] },
  { name: 'Diamondback', tier: 2, aliases: ['diamondback', 'diamond back'] },
  { name: 'Mongoose', tier: 2, aliases: ['mongoose', 'mangoose'], kind: 'bmx', models: [['\\b(dolomite|argus|malus|vinson)\\b', 'fatbike'], ['\\b(tyax|switchback|ruckus|teocali|salvo|pinnacle)\\b', 'mtb_hardtail'], ['.', 'bmx']] },
  { name: 'Haro', tier: 3, aliases: ['haro'], kind: 'bmx', models: [['\\b(shift|saguaro|double peak|flightline|beasley)\\b', 'mtb_hardtail'], ['.', 'bmx']] },
  { name: 'Schwinn', tier: 2, aliases: ['schwinn', 'schwin'] },
  { name: 'Raleigh', tier: 2, aliases: ['raleigh'] },
  { name: 'Peugeot', tier: 2, aliases: ['peugeot'], strict: true },
  { name: 'Batavus', tier: 3, aliases: ['batavus'], models: [['.', 'city']] },
  { name: 'Sparta', tier: 3, aliases: ['sparta'], strict: true, models: [['.', 'city']] },
  { name: 'Koga', tier: 4, aliases: ['koga', 'koga miyata'], models: [['.', 'trekking']] },
  { name: 'Cortina', tier: 2, aliases: ['cortina'], strict: true, models: [['.', 'city']] },
  { name: 'Electra', tier: 3, aliases: ['electra'], models: [['.', 'city']] },
  { name: 'Pegasus', tier: 2, aliases: ['pegasus'] },
  { name: 'Kreidler', tier: 2, aliases: ['kreidler'] },
  { name: 'Hercules', tier: 2, aliases: ['hercules'] },
  { name: 'Kettler', tier: 2, aliases: ['kettler'] },
  { name: 'Diamant', tier: 3, aliases: ['diamant'], strict: true },
  { name: 'Victoria', tier: 2, aliases: ['victoria'], strict: true },
  { name: 'Prophete', tier: 1, aliases: ['prophete'] },
  { name: 'Zündapp', tier: 1, aliases: ['zundapp', 'zuendapp'] },
  { name: 'Fischer', tier: 1, aliases: ['fischer'] },
  { name: 'Telefunken', tier: 1, aliases: ['telefunken'] },
  { name: 'Crivit', tier: 1, aliases: ['crivit'] },
  { name: 'Brompton', tier: 4, aliases: ['brompton'], kind: 'folding', models: [['\\belectric\\b', 'ebike_city'], ['.', 'folding']] },
  { name: 'Dahon', tier: 3, aliases: ['dahon'], kind: 'folding', models: [['.', 'folding']] },
  { name: 'Tern', tier: 4, aliases: ['tern'], strict: true, kind: 'folding', models: [['\\b(gsd|hsd|orox|quick haul)\\b', 'ebike_cargo'], ['\\b(vektron)\\b', 'ebike_city'], ['.', 'folding']] },
  { name: 'Birdy', tier: 4, aliases: ['birdy'], kind: 'folding', models: [['.', 'folding']] },
  { name: 'Strida', tier: 3, aliases: ['strida'], kind: 'folding', models: [['.', 'folding']] },
  { name: 'Urban Arrow', tier: 4, aliases: ['urban arrow'], kind: 'ebike', models: [['.', 'ebike_cargo']] },
  { name: 'Babboe', tier: 3, aliases: ['babboe'], models: [['.', 'cargo']] },
  { name: 'Dartmoor', tier: 3, aliases: ['dartmoor', 'dartmor'], models: [['\\b(two6player|two6 player|gamer|cobra|shine)\\b', 'dirt'], ['\\b(thunderbird|blackbird|bluebird|roots)\\b', 'mtb_full'], ['\\b(hornet|primal|hornet)\\b', 'mtb_hardtail']] },
  { name: 'NS Bikes', tier: 3, aliases: ['ns bikes', 'nsbikes', 'ns bike'], models: [['\\b(zircus|decade|movement|metropolis|soda slope|bfm|clash)\\b', 'dirt'], ['\\b(snabb|define|nerd|soda)\\b', 'mtb_full'], ['\\b(eccentric)\\b', 'mtb_hardtail']] },
  { name: 'Octane One', tier: 3, aliases: ['octane one', 'octane'], models: [['\\b(void|zircus)\\b', 'dirt']] },
  { name: 'Kink', tier: 3, aliases: ['kink'], kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'WeThePeople', tier: 3, aliases: ['wethepeople', 'we the people', 'wtp'], kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Sunday', tier: 3, aliases: ['sunday'], strict: true, kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Cult', tier: 3, aliases: ['cult'], strict: true, kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Subrosa', tier: 3, aliases: ['subrosa'], kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Stolen', tier: 2, aliases: ['stolen'], strict: true, kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Fly Bikes', tier: 3, aliases: ['fly bikes', 'flybikes'], kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Verde', tier: 2, aliases: ['verde'], strict: true, kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Radio', tier: 2, aliases: ['radio bikes'], kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Eastern', tier: 2, aliases: ['eastern bikes'], kind: 'bmx', models: [['.', 'bmx']] },
  { name: 'Muddyfox', tier: 1, aliases: ['muddyfox', 'muddy fox'] },

  // --- Decathlon ---
  { name: 'Btwin', tier: 2, aliases: ['btwin', 'b twin', 'b twinn', 'bitwin', 'decathlon'], models: [['\\b(robot|hello|kids|500|900 hm|run ride|runride)\\b', 'kids'], ['\\b(tilt)\\b', 'folding'], ['\\b(elops)\\b', 'city'], ['\\b(rockrider)\\b', 'mtb_hardtail'], ['\\b(triban)\\b', 'road'], ['\\b(riverside)\\b', 'trekking']] },
  { name: 'Rockrider', tier: 2, aliases: ['rockrider', 'rock rider', 'rokrider'], models: [['\\b(e feel|e expl|e st|e st 500|e st 900|e expl 500|e expl 700|e race)\\b', 'ebike_mtb'], ['\\b(feel|am 100s|am 500s|am 900|xc 100s|race 900s|xc 900s|all mountain)\\b', 'mtb_full'], ['\\b(st|xc|race|expl|explore)\\b', 'mtb_hardtail'], ['.', 'mtb_hardtail']] },
  { name: 'Riverside', tier: 2, aliases: ['riverside', 'river side'], models: [['\\b(e|riverside e|500 e|920 e)\\b', 'ebike_trekking'], ['\\b(touring|920)\\b', 'trekking'], ['.', 'cross']] },
  { name: 'Triban', tier: 2, aliases: ['triban'], models: [['\\b(grvl|gravel|rc 520 gravel)\\b', 'gravel'], ['.', 'road']] },
  { name: 'Van Rysel', tier: 3, aliases: ['van rysel', 'vanrysel'], models: [['\\b(grvl|gravel)\\b', 'gravel'], ['.', 'road']] },
  { name: 'Elops', tier: 2, aliases: ['elops'], models: [['\\b(le|900e|920 e|920e|500e|900 e)\\b', 'ebike_city'], ['.', 'city']] },
  { name: 'Tilt', tier: 2, aliases: ['tilt'], strict: true, kind: 'folding', models: [['.', 'folding']] },

  // --- dětské prémiové ---
  { name: 'Woom', tier: 5, aliases: ['woom', 'woom bike', 'woombike', 'wom'], kind: 'kids', models: [['\\bwoom 1\\b|\\b1 plus\\b', 'balance'], ['\\b(up|now)\\b', 'ebike_kids'], ['.', 'kids']] },
  { name: 'Early Rider', tier: 5, aliases: ['early rider', 'earlyrider', 'early ryder', 'erly rider', 'early rajdr'], kind: 'kids', models: [['\\b(charger|lite|balance|alley runner|classic|road runner|velo)\\b', 'balance'], ['.', 'kids']] },
  { name: 'Kubikes', tier: 4, aliases: ['kubikes', 'kubike', 'ku bikes', 'kubikes', 'ku bike'], kind: 'kids', models: [['.', 'kids']] },
  { name: 'Academy', tier: 4, aliases: ['academy'], kind: 'kids', models: [['\\bgrade 1\\b', 'balance'], ['.', 'kids']] },
  { name: 'Puky', tier: 4, aliases: ['puky', 'pucky'], kind: 'kids', models: [['\\b(lr|lr m|lr l|lr xl|lr ride|lr 1|wutsch|fitsch|pukylino)\\b', 'balance'], ['.', 'kids']] },
  { name: 'Frog', tier: 4, aliases: ['frog bikes', 'frog bike', 'frog'], strict: true, kind: 'kids', models: [['\\b(tadpole)\\b', 'balance'], ['.', 'kids']] },
  { name: 'Beany', tier: 4, aliases: ['beany'], kind: 'kids', models: [['.', 'kids']] },
  { name: 'Islabikes', tier: 4, aliases: ['islabikes', 'isla bikes'], kind: 'kids', models: [['.', 'kids']] },
  { name: 'Cleary', tier: 4, aliases: ['cleary'], kind: 'kids', models: [['.', 'kids']] },
  { name: 'Kokua', tier: 4, aliases: ['kokua', 'likeabike', 'like a bike'], kind: 'kids', models: [['\\b(likeabike|like a bike|jumper)\\b', 'balance'], ['.', 'kids']] },
  { name: 'Strider', tier: 3, aliases: ['strider'], kind: 'kids', models: [['.', 'balance']] },
  { name: 'FirstBIKE', tier: 3, aliases: ['firstbike', 'first bike'], kind: 'kids', models: [['.', 'balance']] },
  { name: 'Ridgeback', tier: 3, aliases: ['ridgeback'], models: [['\\b(mx|dimension|scoot|harmony|melody|terrain)\\b', 'kids']] },
  { name: 'Hornit', tier: 3, aliases: ['hornit'], kind: 'kids', models: [['.', 'kids']] },
  { name: 'Velamos', tier: 1, aliases: ['velamos'], kind: 'vintage' },
  { name: 'Favorit', tier: 1, aliases: ['favorit', 'favorid', 'favourit', 'favoritka', 'favorite'], kind: 'vintage', models: [['.', 'road']] },
  { name: 'Eska', tier: 1, aliases: ['eska'], kind: 'vintage' },
  { name: 'Ukrajina', tier: 1, aliases: ['ukrajina', 'ukraina'], kind: 'vintage' },
];

// Sloučit případné duplicitní položky (stejný název → spojit aliasy)
const DEFS = [];
{
  const seen = new Map();
  for (const b of BRANDS) {
    if (!b.aliases || !b.aliases.length) continue;
    if (seen.has(b.name)) {
      const prev = seen.get(b.name);
      prev.aliases.push(...b.aliases);
      continue;
    }
    const copy = { ...b, aliases: b.aliases.slice() };
    seen.set(b.name, copy);
    DEFS.push(copy);
  }
}

module.exports = { BRANDS: DEFS };
